sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_efba7c7df9d2_key -iv $encrypted_efba7c7df9d2_iv
  -in deploy_key.enc -out deploy_key -d
- docker build -t aadcock/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true aadcock/docker-react npm run test -- --coverage
deploy:
  provider: digitalocean
  region: 
