sudo: required
services:
  - docker
addons:
  ssh_known_hosts: andrewadcock.com
before_install:
  - openssl aes-256-cbc -K $encrypted_efba7c7df9d2_key -iv $encrypted_efba7c7df9d2_iv
    -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - mv deploy_key ~/.ssh/id_rsa
  - docker build -t aadcock/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true aadcock/docker-react npm run test -- --coverage
deploy:
  provider: digitalocean