sudo: required
services:
  - docker
addons:
  ssh_known_hosts:
    - 165.227.179.245
    - andrewadcock.com
before_install:
  - openssl aes-256-cbc -K $encrypted_efba7c7df9d2_key -iv $encrypted_efba7c7df9d2_iv
    -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
  - docker build -t aadcock/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true aadcock/docker-react npm run test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master